/* Bonafide Lyfe — Product Catalog v1.0.0
   Add / edit products here. All pages reference this data. */

window.GB_PRODUCTS = [
  /* ─── HAIR ─────────────────────────────────────────────── */
  {
    id: 1, category: 'hair',
    emoji: '💆‍♀️',
    name: 'Luxury Argan Hair Oil',
    nameEs: 'Aceite de Argán de Lujo para el Cabello',
    price: 24.99, originalPrice: 32.00,
    badge: 'sale',
    description: 'A rich, lightweight oil that tames frizz, adds luminous shine, and nourishes every strand from root to tip. Infused with pure Moroccan argan oil and vitamin E.',
    descriptionEs: 'Un aceite rico y ligero que doma el frizz, agrega brillo luminoso y nutre cada hebra de raíz a punta.',
    benefits: ['Reduces frizz and flyaways', 'Adds brilliant shine', 'Strengthens hair over time', 'Safe for color-treated hair', 'No greasy residue'],
    benefitsEs: ['Reduce el frizz', 'Agrega brillo brillante', 'Fortalece el cabello', 'Seguro para cabello teñido', 'Sin residuo grasoso'],
    rating: 4.8, reviews: 142,
  },
  {
    id: 2, category: 'hair',
    emoji: '🛁',
    name: 'Deep Moisture Shampoo',
    nameEs: 'Champú de Hidratación Profunda',
    price: 18.99,
    badge: 'new',
    description: 'A sulfate-free, moisturizing shampoo formulated to cleanse gently while restoring essential moisture and softness to dry or damaged hair.',
    descriptionEs: 'Un champú sin sulfatos que limpia suavemente mientras restaura la humedad esencial y la suavidad.',
    benefits: ['Sulfate-free formula', 'Restores moisture balance', 'Gentle daily cleanse', 'Suitable for all hair types', 'Color-safe'],
    benefitsEs: ['Fórmula sin sulfatos', 'Restaura el equilibrio de humedad', 'Limpieza diaria suave', 'Apto para todo tipo de cabello'],
    rating: 4.6, reviews: 87,
  },
  {
    id: 3, category: 'hair',
    emoji: '✨',
    name: 'Repair & Restore Conditioner',
    nameEs: 'Acondicionador Reparador',
    price: 18.99,
    description: 'A deeply nourishing conditioner enriched with keratin protein and silk amino acids to restore strength, elasticity, and silkiness to damaged hair.',
    descriptionEs: 'Un acondicionador profundamente nutritivo enriquecido con proteína de keratina y aminoácidos de seda.',
    benefits: ['Repairs damage', 'Detangles effortlessly', 'Restores elasticity', 'Keratin-enriched', 'Reduces breakage'],
    benefitsEs: ['Repara el daño', 'Desenreda sin esfuerzo', 'Restaura elasticidad'],
    rating: 4.7, reviews: 63,
  },
  {
    id: 4, category: 'hair',
    emoji: '🌀',
    name: 'Curl Defining Cream',
    nameEs: 'Crema Definidora de Rizos',
    price: 22.99,
    badge: 'new',
    description: 'Define, hydrate, and control your curls with this lightweight cream that eliminates frizz and enhances natural curl patterns without stiffness.',
    descriptionEs: 'Define, hidrata y controla tus rizos con esta crema ligera que elimina el frizz.',
    benefits: ['Defines curl pattern', 'Long-lasting hold', 'No crunch or stiffness', 'Humidity resistant', 'Vegan formula'],
    benefitsEs: ['Define el patrón de rizos', 'Control duradero', 'Sin rigidez', 'Resistente a la humedad'],
    rating: 4.9, reviews: 211,
  },

  /* ─── COSMETICS ─────────────────────────────────────────── */
  {
    id: 5, category: 'cosmetics',
    emoji: '💄',
    name: 'Velvet Matte Lipstick',
    nameEs: 'Labial Mate Aterciopelado',
    price: 16.99,
    badge: 'sale',
    originalPrice: 22.00,
    description: 'A full-coverage, velvety matte lipstick in rich, bold shades. Formulated with vitamin E and avocado oil to keep lips moisturized all day.',
    descriptionEs: 'Un labial mate aterciopelado de cobertura completa en tonos ricos y audaces.',
    benefits: ['Full coverage', 'All-day wear', 'Moisturizing formula', 'Transfer-resistant', '12 shades available'],
    benefitsEs: ['Cobertura completa', 'Uso todo el día', 'Fórmula hidratante', 'Resistente a transferencia'],
    rating: 4.7, reviews: 328,
  },
  {
    id: 6, category: 'cosmetics',
    emoji: '🌟',
    name: 'Hydrating Foundation',
    nameEs: 'Base Hidratante',
    price: 34.99,
    description: 'A buildable, medium-to-full coverage liquid foundation infused with hyaluronic acid for a natural, luminous finish that lasts up to 16 hours.',
    descriptionEs: 'Una base líquida de cobertura media a completa infusionada con ácido hialurónico para un acabado natural.',
    benefits: ['16-hour wear', 'Hyaluronic acid', '30+ shades available', 'SPF 15', 'Buildable coverage'],
    benefitsEs: ['Uso de 16 horas', 'Ácido hialurónico', 'Más de 30 tonos', 'FPS 15'],
    rating: 4.5, reviews: 196,
  },
  {
    id: 7, category: 'cosmetics',
    emoji: '👁️',
    name: 'Smokey Eye Palette',
    nameEs: 'Paleta de Ojos Ahumados',
    price: 28.99,
    badge: 'new',
    description: '12 richly pigmented eyeshadow shades ranging from neutral nudes to deep smoky tones. Blendable, long-lasting formula for endless eye looks.',
    descriptionEs: '12 sombras de ojos altamente pigmentadas que van desde neutros hasta tonos ahumados profundos.',
    benefits: ['12 versatile shades', 'High pigmentation', 'Easy to blend', '24-hour wear', 'Mirror included'],
    benefitsEs: ['12 tonos versátiles', 'Alta pigmentación', 'Fácil de mezclar', 'Espejo incluido'],
    rating: 4.8, reviews: 155,
  },
  {
    id: 8, category: 'cosmetics',
    emoji: '🖤',
    name: 'Waterproof Mascara',
    nameEs: 'Rímel Resistente al Agua',
    price: 14.99,
    description: 'Buildable volume and length mascara with a curved brush that lifts and separates every lash. Smudge-proof, flake-proof formula.',
    descriptionEs: 'Rímel de volumen y longitud construible con un cepillo curvo que levanta y separa cada pestaña.',
    benefits: ['Waterproof formula', 'Lifts and lengthens', 'No clumping', 'Smudge-proof', 'Easy removal'],
    benefitsEs: ['Fórmula resistente al agua', 'Levanta y alarga', 'Sin grumos'],
    rating: 4.6, reviews: 412,
  },

  /* ─── PERFUME ────────────────────────────────────────────── */
  {
    id: 9, category: 'perfume',
    emoji: '🌹',
    name: 'Rose Bloom Eau de Parfum',
    nameEs: 'Agua de Perfume Rosa en Flor',
    price: 49.99,
    description: 'A romantic, feminine fragrance with top notes of fresh rose petals, heart notes of jasmine and peony, and a warm base of sandalwood and musk.',
    descriptionEs: 'Una fragancia romántica y femenina con notas superiores de pétalos de rosa fresca.',
    benefits: ['Long-lasting scent', '50ml bottle', 'Top: Rose & Citrus', 'Heart: Jasmine & Peony', 'Base: Sandalwood & Musk'],
    benefitsEs: ['Fragancia duradera', 'Frasco de 50ml', 'Notas superiores: Rosa y Cítrico'],
    rating: 4.9, reviews: 89,
  },
  {
    id: 10, category: 'perfume',
    emoji: '🌙',
    name: 'Midnight Oud Fragrance',
    nameEs: 'Fragancia Oud Medianoche',
    price: 54.99,
    badge: 'new',
    description: 'A rich, luxurious unisex fragrance with bold oud wood, smoky incense, and warm amber. An evening scent that commands attention.',
    descriptionEs: 'Una fragancia unisex rica y lujosa con madera de oud audaz, incienso ahumado y ámbar cálido.',
    benefits: ['Unisex fragrance', '50ml bottle', '10-hour longevity', 'Top: Incense & Spice', 'Base: Oud, Amber & Sandalwood'],
    benefitsEs: ['Fragancia unisex', 'Frasco de 50ml', 'Duración de 10 horas'],
    rating: 4.7, reviews: 54,
  },
  {
    id: 11, category: 'perfume',
    emoji: '🍋',
    name: 'Fresh Citrus Body Mist',
    nameEs: 'Bruma Corporal Cítrica Fresca',
    price: 19.99,
    badge: 'sale', originalPrice: 26.00,
    description: 'A light, refreshing body mist bursting with zesty lemon, mandarin, and bergamot. Perfect for everyday wear and post-shower refresh.',
    descriptionEs: 'Una bruma corporal ligera y refrescante con limón, mandarina y bergamota.',
    benefits: ['Refreshing citrus scent', '240ml bottle', 'All-day freshness', 'Alcohol-free formula', 'Hydrates skin'],
    benefitsEs: ['Fragancia cítrica refrescante', 'Frasco de 240ml', 'Frescura todo el día'],
    rating: 4.4, reviews: 133,
  },

  /* ─── JEWELRY ────────────────────────────────────────────── */
  {
    id: 12, category: 'jewelry',
    emoji: '✨',
    name: 'Gold Hoop Earrings',
    nameEs: 'Aretes de Aro Dorados',
    price: 29.99,
    description: 'Classic 18k gold-plated hoop earrings available in three sizes. Hypoallergenic posts make these perfect for sensitive ears.',
    descriptionEs: 'Aretes de aro clásicos chapados en oro de 18k disponibles en tres tamaños.',
    benefits: ['18k gold-plated', 'Hypoallergenic', '3 size options', 'Tarnish-resistant', 'Lightweight design'],
    benefitsEs: ['Chapado en oro de 18k', 'Hipoalergénico', '3 opciones de tamaño'],
    rating: 4.8, reviews: 267,
  },
  {
    id: 13, category: 'jewelry',
    emoji: '💎',
    name: 'Crystal Pendant Necklace',
    nameEs: 'Collar con Colgante de Cristal',
    price: 34.99,
    badge: 'new',
    description: 'A delicate sterling silver chain featuring a sparkling crystal teardrop pendant. Adjustable 16–18" chain, gift-boxed.',
    descriptionEs: 'Una delicada cadena de plata esterlina con un colgante de cristal en forma de lágrima.',
    benefits: ['Sterling silver chain', 'Genuine crystal', 'Adjustable 16–18"', 'Gift box included', 'Hypoallergenic'],
    benefitsEs: ['Cadena de plata esterlina', 'Cristal genuino', 'Caja de regalo incluida'],
    rating: 4.9, reviews: 98,
  },
  {
    id: 14, category: 'jewelry',
    emoji: '💍',
    name: 'Stackable Ring Set',
    nameEs: 'Juego de Anillos Apilables',
    price: 24.99,
    badge: 'sale', originalPrice: 35.00,
    description: 'A set of 5 minimalist stackable rings in gold and silver tones. Mix and match for a curated, layered look.',
    descriptionEs: 'Un juego de 5 anillos apilables minimalistas en tonos dorados y plateados.',
    benefits: ['Set of 5 rings', 'Gold & silver tones', 'Tarnish-resistant', 'Multiple sizes', 'Gift-ready packaging'],
    benefitsEs: ['Juego de 5 anillos', 'Tonos dorados y plateados', 'Resistente al óxido'],
    rating: 4.6, reviews: 184,
  },

  /* ─── SOAP / BODY ────────────────────────────────────────── */
  {
    id: 15, category: 'soap',
    emoji: '🫧',
    name: 'Shea Butter Body Cream',
    nameEs: 'Crema Corporal de Mantequilla de Karité',
    price: 16.99,
    description: 'A rich, non-greasy body cream whipped with pure shea butter, cocoa butter, and vitamin E for 48-hour moisture retention.',
    descriptionEs: 'Una crema corporal rica y no grasosa batida con mantequilla de karité pura, manteca de cacao y vitamina E.',
    benefits: ['48-hour hydration', 'Non-greasy formula', 'Pure shea & cocoa butter', 'Vitamin E enriched', 'All skin types'],
    benefitsEs: ['Hidratación de 48 horas', 'Fórmula no grasosa', 'Mantequilla de karité pura'],
    rating: 4.8, reviews: 220,
  },
  {
    id: 16, category: 'soap',
    emoji: '🍯',
    name: 'Exfoliating Sugar Scrub',
    nameEs: 'Exfoliante de Azúcar',
    price: 14.99,
    badge: 'new',
    description: 'A gentle yet effective sugar scrub infused with honey, coconut oil, and lavender to exfoliate, soften, and illuminate the skin.',
    descriptionEs: 'Un exfoliante de azúcar suave pero efectivo infundido con miel, aceite de coco y lavanda.',
    benefits: ['Removes dead skin cells', 'Honey & coconut oil', 'Gentle on sensitive skin', 'Leaves skin glowing', 'Natural fragrance'],
    benefitsEs: ['Elimina células muertas', 'Miel y aceite de coco', 'Suave para piel sensible'],
    rating: 4.7, reviews: 176,
  },
  {
    id: 17, category: 'soap',
    emoji: '🫐',
    name: 'Lavender Bath Salts',
    nameEs: 'Sales de Baño de Lavanda',
    price: 12.99,
    description: 'Luxurious Himalayan pink salt blended with dried lavender buds and pure lavender essential oil for a deeply relaxing bath experience.',
    descriptionEs: 'Lujosa sal rosada del Himalaya mezclada con capullos de lavanda secos y aceite esencial puro de lavanda.',
    benefits: ['Pure Himalayan salt', 'Real lavender buds', 'Relaxes muscles', 'Promotes sleep', 'Detoxifying'],
    benefitsEs: ['Sal pura del Himalaya', 'Capullos de lavanda reales', 'Relaja músculos', 'Promueve el sueño'],
    rating: 4.9, reviews: 303,
  },

  /* ─── ACCESSORIES ────────────────────────────────────────── */
  {
    id: 18, category: 'accessories',
    emoji: '🎀',
    name: 'Satin Sleep Bonnet',
    nameEs: 'Gorro de Satín para Dormir',
    price: 15.99,
    description: 'A luxurious double-layered satin bonnet that protects your hair while you sleep, reducing breakage, frizz, and moisture loss.',
    descriptionEs: 'Un gorro de satín de doble capa que protege tu cabello mientras duermes.',
    benefits: ['Double-layer satin', 'Elastic band won\'t tangle', 'Reduces breakage', 'One size fits all', 'Machine washable'],
    benefitsEs: ['Satín de doble capa', 'Reduce el quiebre', 'Talla única'],
    rating: 4.8, reviews: 445,
  },
  {
    id: 19, category: 'accessories',
    emoji: '🖌️',
    name: 'Bamboo Makeup Brush Set',
    nameEs: 'Juego de Brochas de Bambú',
    price: 26.99,
    badge: 'new',
    description: '12-piece professional makeup brush set with eco-friendly bamboo handles and ultra-soft synthetic bristles. Includes a travel pouch.',
    descriptionEs: 'Juego de 12 brochas de maquillaje profesionales con mangos de bambú ecológicos y cerdas sintéticas ultra suaves.',
    benefits: ['12-piece set', 'Eco-friendly bamboo', 'Synthetic vegan bristles', 'Travel pouch included', 'Suitable for all products'],
    benefitsEs: ['Juego de 12 piezas', 'Bambú ecológico', 'Cerdas sintéticas veganas', 'Bolsa de viaje incluida'],
    rating: 4.7, reviews: 167,
  },
  {
    id: 20, category: 'accessories',
    emoji: '👜',
    name: 'Cosmetic Travel Bag',
    nameEs: 'Bolso de Viaje para Cosméticos',
    price: 22.99,
    badge: 'sale', originalPrice: 30.00,
    description: 'A roomy, water-resistant travel makeup bag with multiple pockets and a detachable mirror. Perfect for travel or daily organization.',
    descriptionEs: 'Un bolso de maquillaje de viaje amplio y resistente al agua con múltiples bolsillos y espejo desmontable.',
    benefits: ['Water-resistant', 'Multiple pockets', 'Detachable mirror', 'TSA carry-on friendly', 'Wipe-clean interior'],
    benefitsEs: ['Resistente al agua', 'Múltiples bolsillos', 'Espejo desmontable'],
    rating: 4.5, reviews: 92,
  },

  /* ─── WELLNESS ───────────────────────────────────────────── */
  {
    id: 21, category: 'wellness',
    emoji: '💧',
    name: 'Vitamin C Glow Serum',
    nameEs: 'Suero Iluminador de Vitamina C',
    price: 29.99,
    badge: 'new',
    description: 'A powerful 20% Vitamin C serum with hyaluronic acid and niacinamide that brightens, evens skin tone, and protects against free radicals.',
    descriptionEs: 'Un poderoso suero de Vitamina C al 20% con ácido hialurónico y niacinamida que ilumina y unifica el tono.',
    benefits: ['20% Vitamin C', 'Hyaluronic acid', 'Evens skin tone', 'Antioxidant protection', 'Fragrance-free'],
    benefitsEs: ['Vitamina C al 20%', 'Ácido hialurónico', 'Unifica el tono', 'Protección antioxidante'],
    rating: 4.8, reviews: 334,
  },
  {
    id: 22, category: 'wellness',
    emoji: '🌿',
    name: 'Detox Green Tea Mask',
    nameEs: 'Mascarilla Detox de Té Verde',
    price: 18.99,
    description: 'A clarifying clay mask powered by matcha green tea and kaolin clay to draw out impurities, minimize pores, and leave skin refreshed.',
    descriptionEs: 'Una mascarilla de arcilla clarificante con té verde matcha y arcilla de caolín para purificar y minimizar los poros.',
    benefits: ['Kaolin & matcha clay', 'Minimizes pores', 'Removes impurities', 'Weekly treatment', 'Suitable for oily/combination skin'],
    benefitsEs: ['Arcilla de caolín y matcha', 'Minimiza los poros', 'Elimina impurezas'],
    rating: 4.6, reviews: 148,
  },
  {
    id: 23, category: 'wellness',
    emoji: '🌸',
    name: 'Aromatherapy Essential Oil Set',
    nameEs: 'Juego de Aceites Esenciales de Aromaterapia',
    price: 24.99,
    description: 'A curated set of 6 pure essential oils — lavender, peppermint, eucalyptus, tea tree, rose, and lemon — for diffusers, massage, and self-care rituals.',
    descriptionEs: 'Un juego de 6 aceites esenciales puros — lavanda, menta, eucalipto, árbol de té, rosa y limón.',
    benefits: ['6 oils included', '100% pure & natural', 'Lavender, Peppermint, Eucalyptus, Tea Tree, Rose, Lemon', 'Safe for diffusers', 'Gift-ready packaging'],
    benefitsEs: ['6 aceites incluidos', '100% puro y natural', 'Caja de regalo'],
    rating: 4.9, reviews: 257,
  },
];

/* Category metadata */
window.GB_CATEGORIES = [
  { id: 'hair',        emoji: '💆‍♀️', name: 'Hair',        nameEs: 'Cabello',    count: 4 },
  { id: 'cosmetics',   emoji: '💄',    name: 'Cosmetics',   nameEs: 'Cosméticos', count: 4 },
  { id: 'perfume',     emoji: '🌹',    name: 'Perfume',     nameEs: 'Perfume',    count: 3 },
  { id: 'jewelry',     emoji: '💍',    name: 'Jewelry',     nameEs: 'Joyería',    count: 3 },
  { id: 'soap',        emoji: '🫧',    name: 'Soap & Body', nameEs: 'Jabón/Cuerpo', count: 3 },
  { id: 'accessories', emoji: '👜',    name: 'Accessories', nameEs: 'Accesorios', count: 3 },
  { id: 'wellness',    emoji: '🌿',    name: 'Wellness',    nameEs: 'Bienestar',  count: 3 },
];
